resources:
  - name: planning-poker
    icon: github
    type: git
    source:
      url: https://gitlab02.aamegremis.com/alexmegremis/poker-planning.git
      branch: master
  - name: image
    type: registry-image
    icon: docker
    source:
      repository: ((image-name))
      username: ((registry-username))
      password: ((registry-password))
      tag: latest

jobs:
  - name: package
    plan:
    - get: git
    - task: maven-package
      file: git/maven-package.yml
