resources:
  - name: planning-poker
    icon: github
    type: git
    source:
      uri: https://gitlab02.aamegremis.com/alexmegremis/poker-planning.git
      branch: master

jobs:
  - name: package
    plan:
    - get: planning-poker
    - task: maven-package
      file: git/maven-package.yml
